### PR TITLE
Build extension module for all platforms

### LINKED ISSUE #12: Extension module isn't built
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
crcmod tries to build an extension module. gsutil (the Google Cloud Storage CLI client) hopes that it will be available because the extension module is much faster than the pure-python implementation, and complains if it's missing. cf. https://github.com/conda-forge/google-cloud-sdk-feedstock/issues/79

Inspecting the contents of https://anaconda.org/conda-forge/crcmod/1.7/download/linux-64/crcmod-1.7-py38h32f6830_1003.tar.bz2, it does not contain any .so files, so the compiled extension isn't being shipped in the architecture-specific versions of the package that this feedstock builds.

That means that the conda-forge flavour of crcmod can't be used to satisfy gsutil's optional dependency on a compiled crcmod.

It would be nice if the architecture-specific variants contained the extension modules.

### PR DESCRIPTION
**Pull request by nehaljwani**
Resolves https://github.com/conda-forge/crcmod-feedstock/issues/12

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin Please re-render!

**Comment by xylar** [comment]
@nehaljwani, thanks for this.  I'm not expert enough in this package to know whether it is enough to resolve #12, but I'll take your word.  Would you be willing to add yourself as a package maintainer?  Either way, I'll merge as soon as you let me know it's good to go.

**Comment by nehaljwani** [comment]
The additional import added in this PR tests for the existence of the extension module:
```python
(cf) ~/r/c/c/crcmod-1.7 ❯❯❯ grep -C2 crcfun setup.py
ext_modules=[ 
    Extension('crcmod._crcfunext', [os.path.join(base_dir,'src/_crcfunext.c'), ],
    ),
],
```
```zsh
(cf) ~/r/c/c/recipe ❯❯❯ tar -tvf /path/to/crcmod-1.7-py37h14c3975_1006.tar.bz2 | grep _crcfunext
-rwxrwxr-x 1000/1000     21576 2021-06-19 12:11 lib/python3.7/site-packages/crcmod/_crcfunext.cpython-37m-x86_64-linux-gnu.so
```

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@nehaljwani, great, thanks for the explanation. That's what I was assuming.

**Pull request merged**
